# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='BetValue')),
                ('potentialWin', models.FloatField(verbose_name='BetWin')),
                ('isBetSuccessful', models.BooleanField(verbose_name='BetSuccess')),
                ('isActive', models.NullBooleanField(default=True, verbose_name='BetActive')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='null', max_length=64, verbose_name='ClientName')),
                ('email', models.EmailField(max_length=254, verbose_name='ClientMail')),
                ('password', models.CharField(max_length=1024, verbose_name='ClientPassword')),
                ('balance', models.FloatField(verbose_name='ClientBalance')),
                ('logged', models.NullBooleanField(verbose_name='ClientLogged')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Riding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=1, verbose_name='RideName')),
                ('firstHorseChance', models.FloatField(null=True, verbose_name='RideFirstHorseChance')),
                ('secondHorseChance', models.FloatField(null=True, verbose_name='RideSecondHorseChance')),
                ('winner', models.IntegerField(null=True, verbose_name='RideWinner')),
                ('visible', models.NullBooleanField(default=False, verbose_name='RideVisible')),
                ('ready', models.BooleanField(default=False, verbose_name='RidePrognosed')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Client')),
            ],
            bases=('polls.client',),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bet',
            name='ownerLink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client'),
        ),
        migrations.AddField(
            model_name='bet',
            name='rides',
            field=models.ManyToManyField(to='polls.Riding'),
        ),
    ]
