# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initia_l'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetToRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_bet_winner', models.IntegerField(verbose_name='betWinner')),
            ],
        ),
        migrations.RemoveField(
            model_name='bet',
            name='rides',
        ),
        migrations.AddField(
            model_name='bettoride',
            name='bet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Bet'),
        ),
        migrations.AddField(
            model_name='bettoride',
            name='ride_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Riding'),
        ),
    ]
