# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20161128_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettoride',
            name='success',
            field=models.NullBooleanField(default=None, verbose_name='betSucess'),
        ),
    ]
