# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_bettoride_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='isBetSuccessful',
            field=models.NullBooleanField(default=None, verbose_name='BetSuccess'),
        ),
    ]
