# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70f625d11deb15b59796527c547697b8552f9f2bf86cdad8649b170d881f4d525ce7761ca686c58dcf7f8d389632aedd598e22001d1bb8b742e57270ebc4f439

test:
  secret_key_base: ce115b8b183f646dc19dfce045a6503b86590ca12ca95b6202546f1c2240c5d9efd50c1ad3527b4c0b760f48c33f47e48ab91abd52291bcfd5b4fb1bf6680ebb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
